# Generated by Django 4.2.3 on 2023-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_statistics_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='cpc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='cpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
